version: '3.6'
services:
    nginx:
        build: docker/nginx
        ports:
            - '3000:80'
        volumes:
            - './app:/usr/share/nginx/html'
    php-fpm:
        build: docker/php
        volumes:
            - './app:/usr/share/nginx/html'
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
    mariadb:
        image: 'mariadb:10.3'
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - './db_data:/var/lib/mysql'
    composer:
        image: 'composer:2'
        command: install
        volumes:
            - './app:/app'
    node:
        image: "node:14.16.0"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
        volumes:
            - ./app:/home/node/app
        command: "npm start"

    k6:
        image: "loadimpact/k6:latest"
